matrix:
  include:
    - language: node_js 
      node_js:
          - "node"
          - "8"
          - "6"
          - "5"
          - "4"
      script:
          - cd javascript
          - npm install
          - make tests


    - language: python
      python: 3.4
      install:
        - pip install -r python/requirements.txt
        - pip install coveralls
      script:
        - cd python
        - python -m unittest discover
      after_success:
        - coveralls --root ./python

    - os: linux
      language: c 
      cache:
        directories:
          - $HOME/.stack
      script:
        - wget https://get.haskellstack.org/stable/linux-x86_64-static.tar.gz
        - tar -xvf ./linux-x86_64-static.tar.gz
        - cd haskell
        - ../stack-2.1.3-linux-x86_64-static/stack test


    - os: linux
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-7
            - libgmp-dev
            - libz-dev
      script:
        - cmake CMakeLists.txt
        - make
        - ./bin/run_tests

      before_install:
        - pip install --user cpp-coveralls

      after_success:
        - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*" -E ".*googletest.*"


notifications:
  email: false
