matrix:
  include:
    - language: python
      python: 3.4
      script:
        - python -m unittest discover

    - os: linux
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gmp
            - gtest
            - zlib
          script:
            - cmake .

notifications:
  email:
    - michael.a.cornwell@gmail.com