matrix:
  include:
    - language: python
      python: 3.4
      script:
        - python -m unittest discover

    - language: cpp

      install:
        - gem install coveralls-lcov

      addons:
        apt:
          packages:
            - cmake
          sources:
            - kalakris-cmake

      compiler:
        - gcc

      before_install:
        - pip install --user cpp-coveralls

      script:
        - mkdir build
        - cd build
        - cmake ..
        - make
        - cd Line_Test/tests
        - ./run_tests

      after_success:
        - cd -
        - cd Line/CMakeFiles/Line.dir
        - coveralls

"""

    - os: linux
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-7
            - libgmp-dev
            - libz-dev
      script:
        - cmake --target CMakeLists.txt
        - cmake-build-debug/run_tests

      before_install:
        - pip install --user cpp-coveralls

      after_success:
        - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"
        """


notifications:
  email: false
