matrix:
  include:
    - language: python
      python: 3.4
      script:
        - python -m unittest discover

    - os: linux
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-7
            - libgmp-dev
            - libz-dev
      script:
        - cmake --target CMakeLists.txt
        - cmake-build-debug/run_tests
        - ctest

      before_install:
        - pip install --user cpp-coveralls

      after_success:
        - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"


notifications:
  email: false
