matrix:
  include:
    - language: python
      python: 3.4
      script:
        - python -m unittest discover

    - os: linux
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libgmp-dev
            - libz-dev
          script:
            - cmake CMakeLists.txt
            - cmake-build-debug/run_tests

notifications:
  email: false
